#pragma once

#include <string>
#include <vector>
#include <any>
#include <deque>
#include <iterator>
#include <unordered_map>
#include <core/Lexeme.hpp>

enum class typeL{
    link,
    operation,
    mark,
    constant
};

struct VarObject {
    std::uintptr_t addr;
    bool IsReal;
};

struct literal {
    typeL type;
    std::any value;
};

struct GenContext {
    std::unordered_map<std::string, VarObject> VarMap;
    std::deque<int> MarkVector;
    std::vector<literal> OPS;
    int curLex;
    bool InitReal;
    std::vector<Lexeme>& prog;

    // Конструктор
    GenContext(std::vector<Lexeme>& program)
        : curLex(0), InitReal(false), prog(program) {}
};

void sem1(GenContext& ctx);
void sem2(GenContext& ctx);
void sem3(GenContext& ctx);
void sem4(GenContext& ctx);
void sem5(GenContext& ctx);
void sem6(GenContext& ctx);
void sem7(GenContext& ctx);
void sem8(GenContext& ctx);
void sem9(GenContext& ctx);
void sem10(GenContext& ctx);
void sem11(GenContext& ctx);
void sem12(GenContext& ctx);
void sem13(GenContext& ctx);
void sem14(GenContext& ctx);
void sem15(GenContext& ctx);

const std::unordered_map<int, void(*)(GenContext&)> SemanticGenHandlers = {
    {1001, sem1}, 
    {1002, sem2}, 
    {1003, sem3}, 
    {1004, sem4}, 
    {1005, sem5}, 
    {1006, sem6},
    {1007, sem7}, 
    {1008, sem8}, 
    {1009, sem9}, 
    {1010, sem10}, 
    {1011, sem11}
};

enum class GenState {
    A,
    P,
    Q,
    B,
    C, 
    D, 
    S,
    U,
    T,
    V,
    F,
    G,
    H,
    L,
    W,
    M,
    X,
    N,
    O,
    E,
    Z
};

struct GenerationRules {
    std::vector<std::string> pattern; // Правило перехода
    std::vector<int> semGen; // семантические программы для генератора ОПС
};

using GenInnerMap = std::unordered_map<int, GenerationRules>;
using GenTable    = std::unordered_map<GenState, GenInnerMap>;


static const GenTable genTransitionTable = {
    { GenState::A, {
        { 1, GenerationRules{ {"1", "H", "61", "S", "Z", "59", "A" }, { 1, 0, 0, 0, 61, 0, 0 } } },
        { 2, GenerationRules{} },
        { 3, GenerationRules{} },
        { 40, GenerationRules{} },
        { 41, GenerationRules{} },
        { 91, GenerationRules{} },
        { 93, GenerationRules{} },
        { 123, GenerationRules{} },
        { 125, GenerationRules{} },
        { 44, GenerationRules{} },
        { 43, GenerationRules{} },
        { 45, GenerationRules{} },
        { 42, GenerationRules{} },
        { 47, GenerationRules{} },
        { 61, GenerationRules{} },
        { 60, GenerationRules{} },
        { 7, GenerationRules{} },
        { 5, GenerationRules{} },
        { 4, GenerationRules{} },
        { 6, GenerationRules{} },
        { 62, GenerationRules{} },
        { 59, GenerationRules{} },
        { 8, GenerationRules{} },
        { 33, GenerationRules{} },
        { 9, GenerationRules{} },
        { 20, GenerationRules{ {"20", "P", "59", "A" }, { 1010, 0, 0, 0 } } },
        { 21, GenerationRules{ {"21", "P", "59", "A" }, { 1011, 0, 0, 0 } } },
        { 10, GenerationRules{ {"10", "40", "L", "41", "123", "A", "125", "E", "Z", "A" }, { 0, 0, 0, 0, 1001, 0, 0, 0, 1003, 0 } } },
        { 11, GenerationRules{} },
        { 12, GenerationRules{ {"12", "40", "L", "41", "123", "A", "125", "Z", "A" }, { 1004, 0, 0, 0, 1001, 0, 0, 1005, 0 } } },
        { 13, GenerationRules{ {"13", "40", "1", "H", "41", "59", "A" }, { 0, 0, 1, 0, 1101, 0, 0 } } },
        { 14, GenerationRules{ {"14", "40", "S", "41", "59", "A" }, { 0, 0, 0, 1102, 0, 0 } } },
        { 15, GenerationRules{} },
        { 16, GenerationRules{} },
        { 17, GenerationRules{} },
        { 18, GenerationRules{} },
        { 19, GenerationRules{} },
        { 22, GenerationRules{} },
    }},
    { GenState::P, {
        { 1, GenerationRules{ {"1", "B", "Q" }, { 1006, 0, 1009 } } },
    }},
    { GenState::Q, {
        { 1, GenerationRules{} },
        { 2, GenerationRules{} },
        { 3, GenerationRules{} },
        { 40, GenerationRules{} },
        { 41, GenerationRules{} },
        { 91, GenerationRules{} },
        { 93, GenerationRules{} },
        { 123, GenerationRules{} },
        { 125, GenerationRules{} },
        { 44, GenerationRules{ {"44", "1", "B", "Q" }, { 0, 1006, 0, 1009 } } },
        { 43, GenerationRules{} },
        { 45, GenerationRules{} },
        { 42, GenerationRules{} },
        { 47, GenerationRules{} },
        { 61, GenerationRules{} },
        { 60, GenerationRules{} },
        { 7, GenerationRules{} },
        { 5, GenerationRules{} },
        { 4, GenerationRules{} },
        { 6, GenerationRules{} },
        { 62, GenerationRules{} },
        { 59, GenerationRules{} },
        { 8, GenerationRules{} },
        { 33, GenerationRules{} },
        { 9, GenerationRules{} },
        { 20, GenerationRules{} },
        { 21, GenerationRules{} },
        { 10, GenerationRules{} },
        { 11, GenerationRules{} },
        { 12, GenerationRules{} },
        { 13, GenerationRules{} },
        { 14, GenerationRules{} },
        { 15, GenerationRules{} },
        { 16, GenerationRules{} },
        { 17, GenerationRules{} },
        { 18, GenerationRules{} },
        { 19, GenerationRules{} },
        { 22, GenerationRules{} },
    }},
    { GenState::B, {
        { 1, GenerationRules{} },
        { 2, GenerationRules{} },
        { 3, GenerationRules{} },
        { 40, GenerationRules{} },
        { 41, GenerationRules{} },
        { 91, GenerationRules{ {"91", "2", "93", "C" }, { 0, 2, 0, 0 } } },
        { 93, GenerationRules{} },
        { 123, GenerationRules{} },
        { 125, GenerationRules{} },
        { 44, GenerationRules{} },
        { 43, GenerationRules{} },
        { 45, GenerationRules{} },
        { 42, GenerationRules{} },
        { 47, GenerationRules{} },
        { 61, GenerationRules{ {"61", "S", "Z" }, { 1007, 0, 61 } } },
        { 60, GenerationRules{} },
        { 7, GenerationRules{} },
        { 5, GenerationRules{} },
        { 4, GenerationRules{} },
        { 6, GenerationRules{} },
        { 62, GenerationRules{} },
        { 59, GenerationRules{} },
        { 8, GenerationRules{} },
        { 33, GenerationRules{} },
        { 9, GenerationRules{} },
        { 20, GenerationRules{} },
        { 21, GenerationRules{} },
        { 10, GenerationRules{} },
        { 11, GenerationRules{} },
        { 12, GenerationRules{} },
        { 13, GenerationRules{} },
        { 14, GenerationRules{} },
        { 15, GenerationRules{} },
        { 16, GenerationRules{} },
        { 17, GenerationRules{} },
        { 18, GenerationRules{} },
        { 19, GenerationRules{} },
        { 22, GenerationRules{} },
    }},
    { GenState::C, {
        { 1, GenerationRules{} },
        { 2, GenerationRules{} },
        { 3, GenerationRules{} },
        { 40, GenerationRules{} },
        { 41, GenerationRules{} },
        { 91, GenerationRules{} },
        { 93, GenerationRules{} },
        { 123, GenerationRules{} },
        { 125, GenerationRules{} },
        { 44, GenerationRules{} },
        { 43, GenerationRules{} },
        { 45, GenerationRules{} },
        { 42, GenerationRules{} },
        { 47, GenerationRules{} },
        { 61, GenerationRules{ { "61", "123", "S", "D", "125" }, { 0, 0, 0, 0, 1008 } } },
        { 60, GenerationRules{} },
        { 7, GenerationRules{} },
        { 5, GenerationRules{} },
        { 4, GenerationRules{} },
        { 6, GenerationRules{} },
        { 62, GenerationRules{} },
        { 59, GenerationRules{} },
        { 8, GenerationRules{} },
        { 33, GenerationRules{} },
        { 9, GenerationRules{} },
        { 20, GenerationRules{} },
        { 21, GenerationRules{} },
        { 10, GenerationRules{} },
        { 11, GenerationRules{} },
        { 12, GenerationRules{} },
        { 13, GenerationRules{} },
        { 14, GenerationRules{} },
        { 15, GenerationRules{} },
        { 16, GenerationRules{} },
        { 17, GenerationRules{} },
        { 18, GenerationRules{} },
        { 19, GenerationRules{} },
        { 22, GenerationRules{} },
    }},
    { GenState::D, {
        { 1, GenerationRules{} },
        { 2, GenerationRules{} },
        { 3, GenerationRules{} },
        { 40, GenerationRules{} },
        { 41, GenerationRules{} },
        { 91, GenerationRules{} },
        { 93, GenerationRules{} },
        { 123, GenerationRules{} },
        { 125, GenerationRules{} },
        { 44, GenerationRules{ { "44", "S", "D" }, { 0, 0, 0 } } },
        { 43, GenerationRules{} },
        { 45, GenerationRules{} },
        { 42, GenerationRules{} },
        { 47, GenerationRules{} },
        { 61, GenerationRules{} },
        { 60, GenerationRules{} },
        { 7, GenerationRules{} },
        { 5, GenerationRules{} },
        { 4, GenerationRules{} },
        { 6, GenerationRules{} },
        { 62, GenerationRules{} },
        { 59, GenerationRules{} },
        { 8, GenerationRules{} },
        { 33, GenerationRules{} },
        { 9, GenerationRules{} },
        { 20, GenerationRules{} },
        { 21, GenerationRules{} },
        { 10, GenerationRules{} },
        { 11, GenerationRules{} },
        { 12, GenerationRules{} },
        { 13, GenerationRules{} },
        { 14, GenerationRules{} },
        { 15, GenerationRules{} },
        { 16, GenerationRules{} },
        { 17, GenerationRules{} },
        { 18, GenerationRules{} },
        { 19, GenerationRules{} },
        { 22, GenerationRules{} },
    }},
    { GenState::S, {
        { 1, GenerationRules{ {"1", "H", "V", "U" }, { 1, 0, 0, 0 } } },
        { 2, GenerationRules{ {"2", "V", "U" }, { 2, 0, 0 } } },
        { 3, GenerationRules{ {"3", "V", "U" }, { 3, 0, 0 } } },
        { 40, GenerationRules{ {"40", "S", "41", "V", "U" }, { 0, 0, 0, 0, 0 } } },
        { 45, GenerationRules{ {"45", "G", "V", "U" }, { 0, 0, 1100, 0 } } },
        { 15, GenerationRules{ {"15", "40", "S", "41", "V", "U" }, { 0, 0, 0, 1103, 0, 0 } } },
        { 16, GenerationRules{ {"16", "40", "S", "41", "V", "U" }, { 0, 0, 0, 1104, 0, 0 } } },
        { 17, GenerationRules{ {"17", "40", "S", "41", "V", "U" }, { 0, 0, 0, 1105, 0, 0 } } },
        { 18, GenerationRules{ {"18", "40", "S", "41", "V", "U" }, { 0, 0, 0, 1106, 0, 0 } } },
        { 19, GenerationRules{ {"19", "40", "S", "41", "V", "U" }, { 0, 0, 0, 1107, 0, 0 } } },
    }},
    { GenState::U, {
        { 1, GenerationRules{} },
        { 2, GenerationRules{} },
        { 3, GenerationRules{} },
        { 40, GenerationRules{} },
        { 41, GenerationRules{} },
        { 91, GenerationRules{} },
        { 93, GenerationRules{} },
        { 123, GenerationRules{} },
        { 125, GenerationRules{} },
        { 44, GenerationRules{} },
        { 43, GenerationRules{ {"43", "T", "U" }, { 0, 0, 43 } } },
        { 45, GenerationRules{ {"45", "T", "U" }, { 0, 0, 45 } } },
        { 42, GenerationRules{} },
        { 47, GenerationRules{} },
        { 61, GenerationRules{} },
        { 60, GenerationRules{} },
        { 7, GenerationRules{} },
        { 5, GenerationRules{} },
        { 4, GenerationRules{} },
        { 6, GenerationRules{} },
        { 62, GenerationRules{} },
        { 59, GenerationRules{} },
        { 8, GenerationRules{} },
        { 33, GenerationRules{} },
        { 9, GenerationRules{} },
        { 20, GenerationRules{} },
        { 21, GenerationRules{} },
        { 10, GenerationRules{} },
        { 11, GenerationRules{} },
        { 12, GenerationRules{} },
        { 13, GenerationRules{} },
        { 14, GenerationRules{} },
        { 15, GenerationRules{} },
        { 16, GenerationRules{} },
        { 17, GenerationRules{} },
        { 18, GenerationRules{} },
        { 19, GenerationRules{} },
        { 22, GenerationRules{} },
    }},
    { GenState::T, {
        { 1, GenerationRules{ {"1", "H", "V" }, { 1, 0, 0 } } },
        { 2, GenerationRules{ {"2", "V" }, { 2, 0 } } },
        { 3, GenerationRules{ {"3", "V" }, { 3, 0 } } },
        { 40, GenerationRules{ {"40", "S", "41", "V" }, { 0, 0, 0, 0 } } },
        { 45, GenerationRules{ {"45", "G", "V"}, { 0, 0, 1100 } } },
        { 15, GenerationRules{ {"15", "40", "S", "41", "V" }, { 0, 0, 0, 1103, 0 } } },
        { 16, GenerationRules{ {"16", "40", "S", "41", "V" }, { 0, 0, 0, 1104, 0 } } },
        { 17, GenerationRules{ {"17", "40", "S", "41", "V" }, { 0, 0, 0, 1105, 0 } } },
        { 18, GenerationRules{ {"18", "40", "S", "41", "V" }, { 0, 0, 0, 1106, 0 } } },
        { 19, GenerationRules{ {"19", "40", "S", "41", "V" }, { 0, 0, 0, 1107, 0 } } },
    }},
    { GenState::V, {
        { 1, GenerationRules{} },
        { 2, GenerationRules{} },
        { 3, GenerationRules{} },
        { 40, GenerationRules{} },
        { 41, GenerationRules{} },
        { 91, GenerationRules{} },
        { 93, GenerationRules{} },
        { 123, GenerationRules{} },
        { 125, GenerationRules{} },
        { 44, GenerationRules{} },
        { 43, GenerationRules{} },
        { 45, GenerationRules{} },
        { 42, GenerationRules{ {"42", "F", "V" }, { 0, 0, 42 } } },
        { 47, GenerationRules{ {"47", "F", "V" }, { 0, 0, 47 } } },
        { 61, GenerationRules{} },
        { 60, GenerationRules{} },
        { 7, GenerationRules{} },
        { 5, GenerationRules{} },
        { 4, GenerationRules{} },
        { 6, GenerationRules{} },
        { 62, GenerationRules{} },
        { 59, GenerationRules{} },
        { 8, GenerationRules{} },
        { 33, GenerationRules{} },
        { 9, GenerationRules{} },
        { 20, GenerationRules{} },
        { 21, GenerationRules{} },
        { 10, GenerationRules{} },
        { 11, GenerationRules{} },
        { 12, GenerationRules{} },
        { 13, GenerationRules{} },
        { 14, GenerationRules{} },
        { 15, GenerationRules{} },
        { 16, GenerationRules{} },
        { 17, GenerationRules{} },
        { 18, GenerationRules{} },
        { 19, GenerationRules{} },
        { 22, GenerationRules{} },
    }},
    { GenState::F, {
        { 1, GenerationRules{ {"1", "H" }, { 1, 0 } } },
        { 2, GenerationRules{ {"2" }, { 2 } } },
        { 3, GenerationRules{ {"3" }, { 3 } } },
        { 40, GenerationRules{ {"40", "S", "41" }, { 0, 0, 0 } } },
        { 45, GenerationRules{ {"45", "G", "Z"}, { 0, 0, 1100 } } },
        { 15, GenerationRules{ {"15", "40", "S", "41" }, { 0, 0, 0, 1103 } } },
        { 16, GenerationRules{ {"16", "40", "S", "41" }, { 0, 0, 0, 1104 } } },
        { 17, GenerationRules{ {"17", "40", "S", "41" }, { 0, 0, 0, 1105 } } },
        { 18, GenerationRules{ {"18", "40", "S", "41" }, { 0, 0, 0, 1106 } } },
        { 19, GenerationRules{ {"19", "40", "S", "41" }, { 0, 0, 0, 1107 } } },
    }},
    { GenState::G, {
        { 1, GenerationRules{ {"1", "H" }, { 1, 0 } } },
        { 2, GenerationRules{ {"2" }, { 2 } } },
        { 3, GenerationRules{ {"3" }, { 3 } } },
        { 40, GenerationRules{ {"40", "S", "41" }, { 0, 0, 0 } } },
        { 15, GenerationRules{ {"15", "40", "S", "41" }, { 0, 0, 0, 1103 } } },
        { 16, GenerationRules{ {"16", "40", "S", "41" }, { 0, 0, 0, 1104 } } },
        { 17, GenerationRules{ {"17", "40", "S", "41" }, { 0, 0, 0, 1105 } } },
        { 18, GenerationRules{ {"18", "40", "S", "41" }, { 0, 0, 0, 1106 } } },
        { 19, GenerationRules{ {"19", "40", "S", "41" }, { 0, 0, 0, 1107 } } },
    }},
    { GenState::H, {
        { 1, GenerationRules{} },
        { 2, GenerationRules{} },
        { 3, GenerationRules{} },
        { 40, GenerationRules{} },
        { 41, GenerationRules{} },
        { 91, GenerationRules{ {"91", "S", "93" }, { 0, 0, 1108 } } },
        { 93, GenerationRules{} },
        { 123, GenerationRules{} },
        { 125, GenerationRules{} },
        { 44, GenerationRules{} },
        { 43, GenerationRules{} },
        { 45, GenerationRules{} },
        { 42, GenerationRules{} },
        { 47, GenerationRules{} },
        { 61, GenerationRules{} },
        { 60, GenerationRules{} },
        { 7, GenerationRules{} },
        { 5, GenerationRules{} },
        { 4, GenerationRules{} },
        { 6, GenerationRules{} },
        { 62, GenerationRules{} },
        { 59, GenerationRules{} },
        { 8, GenerationRules{} },
        { 33, GenerationRules{} },
        { 9, GenerationRules{} },
        { 20, GenerationRules{} },
        { 21, GenerationRules{} },
        { 10, GenerationRules{} },
        { 11, GenerationRules{} },
        { 12, GenerationRules{} },
        { 13, GenerationRules{} },
        { 14, GenerationRules{} },
        { 15, GenerationRules{} },
        { 16, GenerationRules{} },
        { 17, GenerationRules{} },
        { 18, GenerationRules{} },
        { 19, GenerationRules{} },
        { 22, GenerationRules{} },
    }},
    { GenState::L, {
        { 1, GenerationRules{ {"1", "H", "V", "U", "O", "X", "W" }, { 1, 0, 0, 0, 0, 0, 0 } } },
        { 2, GenerationRules{ {"2", "V", "U", "O", "X", "W" }, { 2, 0, 0, 0, 0, 0 } } },
        { 3, GenerationRules{ {"3", "V", "U", "O", "X", "W" }, { 3, 0, 0, 0, 0, 0 } } },
        { 40, GenerationRules{ {"40", "L", "41", "X", "W" }, { 0, 0, 0, 0, 0 } } },
        { 45, GenerationRules{ {"45", "G", "Z", "V", "U", "O", "X", "W" }, { 0, 0, 1100, 0, 0, 0, 0, 0 } } },
        { 33, GenerationRules{ {"33", "40", "L", "41", "X", "W" }, { 0, 0, 0, 0, 33, 0 } } },
        { 15, GenerationRules{ {"15", "40", "S", "41", "V", "U", "O", "X", "W" }, { 0, 0, 0, 1103, 0, 0, 0, 0, 0 } } },
        { 16, GenerationRules{ {"16", "40", "S", "41", "V", "U", "O", "X", "W" }, { 0, 0, 0, 1104, 0, 0, 0, 0, 0  } } },
        { 17, GenerationRules{ {"17", "40", "S", "41", "V", "U", "O", "X", "W" }, { 0, 0, 0, 1105, 0, 0, 0, 0, 0  } } },
        { 18, GenerationRules{ {"18", "40", "S", "41", "V", "U", "O", "X", "W" }, { 0, 0, 0, 1106, 0, 0, 0, 0, 0  } } },
        { 19, GenerationRules{ {"19", "40", "S", "41", "V", "U", "O", "X", "W" }, { 0, 0, 0, 1107, 0, 0, 0, 0, 0  } } },
    }},
    { GenState::W, {
        { 1, GenerationRules{} },
        { 2, GenerationRules{} },
        { 3, GenerationRules{} },
        { 40, GenerationRules{} },
        { 41, GenerationRules{} },
        { 91, GenerationRules{} },
        { 93, GenerationRules{} },
        { 123, GenerationRules{} },
        { 125, GenerationRules{} },
        { 44, GenerationRules{} },
        { 43, GenerationRules{} },
        { 45, GenerationRules{} },
        { 42, GenerationRules{} },
        { 47, GenerationRules{} },
        { 61, GenerationRules{} },
        { 60, GenerationRules{} },
        { 7, GenerationRules{} },
        { 5, GenerationRules{} },
        { 4, GenerationRules{} },
        { 6, GenerationRules{} },
        { 62, GenerationRules{} },
        { 59, GenerationRules{} },
        { 8, GenerationRules{ {"8", "M", "W" }, { 0, 0, 8 } } },
        { 33, GenerationRules{} },
        { 9, GenerationRules{} },
        { 20, GenerationRules{} },
        { 21, GenerationRules{} },
        { 10, GenerationRules{} },
        { 11, GenerationRules{} },
        { 12, GenerationRules{} },
        { 13, GenerationRules{} },
        { 14, GenerationRules{} },
        { 15, GenerationRules{} },
        { 16, GenerationRules{} },
        { 17, GenerationRules{} },
        { 18, GenerationRules{} },
        { 19, GenerationRules{} },
        { 22, GenerationRules{} },
    }},
    { GenState::M, {
        { 1, GenerationRules{ {"1", "H", "V", "U", "O", "X" }, { 1, 0, 0, 0, 0, 0  } } },
        { 2, GenerationRules{ {"2", "V", "U", "O", "X" }, { 2, 0, 0, 0, 0  } } },
        { 3, GenerationRules{ {"3", "V", "U", "O", "X" }, { 3, 0, 0, 0, 0  } } },
        { 40, GenerationRules{ {"40", "L", "41", "X" }, { 0, 0, 0, 0  } } },
        { 45, GenerationRules{ {"45", "G", "Z", "V", "U", "O", "X" }, { 0, 0, 1100, 0, 0, 0, 0  } } },
        { 33, GenerationRules{ {"33", "40", "L", "41", "X" }, { 0, 0, 0, 0, 33 } } },
        { 15, GenerationRules{ {"15", "40", "S", "41", "V", "U", "O", "X" }, { 0, 0, 0, 1103, 0, 0, 0, 0  } } },
        { 16, GenerationRules{ {"16", "40", "S", "41", "V", "U", "O", "X" }, { 0, 0, 0, 1104, 0, 0, 0, 0  } } },
        { 17, GenerationRules{ {"17", "40", "S", "41", "V", "U", "O", "X" }, { 0, 0, 0, 1105, 0, 0, 0, 0  } } },
        { 18, GenerationRules{ {"18", "40", "S", "41", "V", "U", "O", "X" }, { 0, 0, 0, 1106, 0, 0, 0, 0  } } },
        { 19, GenerationRules{ {"19", "40", "S", "41", "V", "U", "O", "X" }, { 0, 0, 0, 1107, 0, 0, 0, 0  } } },
    }},
    { GenState::X, {
        { 1, GenerationRules{} },
        { 2, GenerationRules{} },
        { 3, GenerationRules{} },
        { 40, GenerationRules{} },
        { 41, GenerationRules{} },
        { 91, GenerationRules{} },
        { 93, GenerationRules{} },
        { 123, GenerationRules{} },
        { 125, GenerationRules{} },
        { 44, GenerationRules{} },
        { 43, GenerationRules{} },
        { 45, GenerationRules{} },
        { 42, GenerationRules{} },
        { 47, GenerationRules{} },
        { 61, GenerationRules{} },
        { 60, GenerationRules{} },
        { 7, GenerationRules{} },
        { 5, GenerationRules{} },
        { 4, GenerationRules{} },
        { 6, GenerationRules{} },
        { 62, GenerationRules{} },
        { 59, GenerationRules{} },
        { 8, GenerationRules{} },
        { 33, GenerationRules{} },
        { 9, GenerationRules{ {"9", "N", "X" }, { 0, 0, 9 } } },
        { 20, GenerationRules{} },
        { 21, GenerationRules{} },
        { 10, GenerationRules{} },
        { 11, GenerationRules{} },
        { 12, GenerationRules{} },
        { 13, GenerationRules{} },
        { 14, GenerationRules{} },
        { 15, GenerationRules{} },
        { 16, GenerationRules{} },
        { 17, GenerationRules{} },
        { 18, GenerationRules{} },
        { 19, GenerationRules{} },
        { 22, GenerationRules{} },
    }},
    { GenState::N, {
        { 1, GenerationRules{ {"1", "H", "V", "U", "O" }, { 1, 0, 0, 0, 0  } } },
        { 2, GenerationRules{ {"2", "V", "U", "O" }, { 2, 0, 0, 0  } } },
        { 3, GenerationRules{ {"3", "V", "U", "O" }, { 3, 0, 0, 0  } } },
        { 40, GenerationRules{ {"40", "L", "41" }, { 0, 0, 0  } } },
        { 45, GenerationRules{ {"45", "G", "Z", "V", "U", "O" }, { 0, 0, 1100, 0, 0, 0  } } },
        { 33, GenerationRules{ {"33", "40", "L", "41", "Z" }, { 0, 0, 0, 0, 33 } } },
        { 15, GenerationRules{ {"15", "40", "S", "41", "V", "U", "O" }, { 0, 0, 0, 1103, 0, 0, 0  } } },
        { 16, GenerationRules{ {"16", "40", "S", "41", "V", "U", "O" }, { 0, 0, 0, 1104, 0, 0, 0  } } },
        { 17, GenerationRules{ {"17", "40", "S", "41", "V", "U", "O" }, { 0, 0, 0, 1105, 0, 0, 0  } } },
        { 18, GenerationRules{ {"18", "40", "S", "41", "V", "U", "O" }, { 0, 0, 0, 1106, 0, 0, 0  } } },
        { 19, GenerationRules{ {"19", "40", "S", "41", "V", "U", "O" }, { 0, 0, 0, 1107, 0, 0, 0  } } },
    }},
    { GenState::O, {
        { 60, GenerationRules{ {"60", "S", "Z" }, { 0, 0, 60 } } },
        { 7, GenerationRules{ {"7", "S", "Z" }, { 0, 0, 7 } } },
        { 5, GenerationRules{ {"5", "S", "Z" }, { 0, 0, 5 } } },
        { 4, GenerationRules{ {"4", "S", "Z" }, { 0, 0, 4 } } },
        { 6, GenerationRules{ {"6", "S", "Z" }, { 0, 0, 6 } } },
        { 62, GenerationRules{ {"62", "S", "Z" }, { 0, 0, 62 } } },
    }},
    { GenState::E, {
        { 1, GenerationRules{} },
        { 2, GenerationRules{} },
        { 3, GenerationRules{} },
        { 40, GenerationRules{} },
        { 41, GenerationRules{} },
        { 91, GenerationRules{} },
        { 93, GenerationRules{} },
        { 123, GenerationRules{} },
        { 125, GenerationRules{} },
        { 44, GenerationRules{} },
        { 43, GenerationRules{} },
        { 45, GenerationRules{} },
        { 42, GenerationRules{} },
        { 47, GenerationRules{} },
        { 61, GenerationRules{} },
        { 60, GenerationRules{} },
        { 7, GenerationRules{} },
        { 5, GenerationRules{} },
        { 4, GenerationRules{} },
        { 6, GenerationRules{} },
        { 62, GenerationRules{} },
        { 59, GenerationRules{} },
        { 8, GenerationRules{} },
        { 33, GenerationRules{} },
        { 9, GenerationRules{} },
        { 20, GenerationRules{} },
        { 21, GenerationRules{} },
        { 10, GenerationRules{} },
        { 11, GenerationRules{ {"11", "123", "A", "125" }, { 1002, 0, 0, 0 } } },
        { 12, GenerationRules{} },
        { 13, GenerationRules{} },
        { 14, GenerationRules{} },
        { 15, GenerationRules{} },
        { 16, GenerationRules{} },
        { 17, GenerationRules{} },
        { 18, GenerationRules{} },
        { 19, GenerationRules{} },
        { 22, GenerationRules{} },
    }},
    { GenState::Z, {
        { 1, GenerationRules{} },
        { 2, GenerationRules{} },
        { 3, GenerationRules{} },
        { 40, GenerationRules{} },
        { 41, GenerationRules{} },
        { 91, GenerationRules{} },
        { 93, GenerationRules{} },
        { 123, GenerationRules{} },
        { 125, GenerationRules{} },
        { 44, GenerationRules{} },
        { 43, GenerationRules{} },
        { 45, GenerationRules{} },
        { 42, GenerationRules{} },
        { 47, GenerationRules{} },
        { 61, GenerationRules{} },
        { 60, GenerationRules{} },
        { 7, GenerationRules{} },
        { 5, GenerationRules{} },
        { 4, GenerationRules{} },
        { 6, GenerationRules{} },
        { 62, GenerationRules{} },
        { 59, GenerationRules{} },
        { 8, GenerationRules{} },
        { 33, GenerationRules{} },
        { 9, GenerationRules{} },
        { 20, GenerationRules{} },
        { 21, GenerationRules{} },
        { 10, GenerationRules{} },
        { 11, GenerationRules{} },
        { 12, GenerationRules{} },
        { 13, GenerationRules{} },
        { 14, GenerationRules{} },
        { 15, GenerationRules{} },
        { 16, GenerationRules{} },
        { 17, GenerationRules{} },
        { 18, GenerationRules{} },
        { 19, GenerationRules{} },
        { 22, GenerationRules{} },
    }}
};

std::vector<literal> genOPS(const std::vector<Lexeme>& prog);