#ifndef GENOPS_H
#define GENOPS_H

#include <genOPS/Structs.h>
#include <core/Literal.hpp>
#include <deque>

std::vector<std::unique_ptr<Literal>> genOPS(std::vector<Lexeme>& prog);

using GenInnerMap = std::unordered_map<int, GenRules>;
using GenTable    = std::unordered_map<GenState, GenInnerMap>;

void GenSem1(GenContext& ctx);
void GenSem2(GenContext& ctx);
void GenSem3(GenContext& ctx);
void GenSem4(GenContext& ctx);
void GenSem5(GenContext& ctx);
void GenSem6(GenContext& ctx);
void GenSem7(GenContext& ctx);
void GenSem8(GenContext& ctx);
void GenSem9(GenContext& ctx);
void GenSem10(GenContext& ctx);
void GenSem11(GenContext& ctx);

const std::unordered_map<int, void(*)(GenContext&)> SemanticGenHandlers = {
    {1001, GenSem1},
    {1002, GenSem2},
    {1003, GenSem3},
    {1004, GenSem4},
    {1005, GenSem5},
    {1006, GenSem6},
    {1007, GenSem7},
    {1008, GenSem8},
    {1009, GenSem9},
    {1010, GenSem10},
    {1011, GenSem11}
};

static const std::unordered_map<std::string,GenState> getState = {
    {"A", GenState::A}, {"P", GenState::P}, {"Q", GenState::Q},
    {"B", GenState::B}, {"C", GenState::C}, {"D", GenState::D},
    {"S", GenState::S}, {"U", GenState::U}, {"T", GenState::T},
    {"V", GenState::V}, {"F", GenState::F}, {"G", GenState::G},
    {"H", GenState::H}, {"L", GenState::L}, {"W", GenState::W},
    {"M", GenState::M}, {"X", GenState::X}, {"N", GenState::N},
    {"O", GenState::O}, {"E", GenState::E}, {"Z", GenState::Z},
    {"#", GenState::Z}
};

static const GenTable genTransitionTable = {
    { GenState::A, {
                   { 1, GenRules{ {"1", "H", "61", "S", "Z", "59", "A" }, { 1, 0, 0, 0, 61, 0, 0 } } },
                   { 2, GenRules{} },
                   { 3, GenRules{} },
                   { 40, GenRules{} },
                   { 41, GenRules{} },
                   { 91, GenRules{} },
                   { 93, GenRules{} },
                   { 123, GenRules{} },
                   { 125, GenRules{} },
                   { 44, GenRules{} },
                   { 43, GenRules{} },
                   { 45, GenRules{} },
                   { 42, GenRules{} },
                   { 47, GenRules{} },
                   { 61, GenRules{} },
                   { 60, GenRules{} },
                   { 7, GenRules{} },
                   { 5, GenRules{} },
                   { 4, GenRules{} },
                   { 6, GenRules{} },
                   { 62, GenRules{} },
                   { 59, GenRules{} },
                   { 8, GenRules{} },
                   { 33, GenRules{} },
                   { 9, GenRules{} },
                   { 20, GenRules{ {"20", "P", "59", "A" }, { 1010, 0, 0, 0 } } },
                   { 21, GenRules{ {"21", "P", "59", "A" }, { 1011, 0, 0, 0 } } },
                   { 10, GenRules{ {"10", "40", "L", "41", "123", "A", "125", "E", "Z", "A" }, { 0, 0, 0, 0, 1001, 0, 0, 0, 1003, 0 } } },
                   { 11, GenRules{} },
                   { 12, GenRules{ {"12", "40", "L", "41", "123", "A", "125", "Z", "A" }, { 1004, 0, 0, 0, 1001, 0, 0, 1005, 0 } } },
                   { 13, GenRules{ {"13", "40", "1", "H", "41", "59", "A" }, { 0, 0, 1, 0, 1101, 0, 0 } } },
                   { 14, GenRules{ {"14", "40", "S", "41", "59", "A" }, { 0, 0, 0, 1102, 0, 0 } } },
                   { 15, GenRules{} },
                   { 16, GenRules{} },
                   { 17, GenRules{} },
                   { 18, GenRules{} },
                   { 19, GenRules{} },
                   { 22, GenRules{} },
                   }},
    { GenState::P, {
                   { 1, GenRules{ {"1", "B", "Q" }, { 1006, 0, 1009 } } },
                   }},
    { GenState::Q, {
                   { 1, GenRules{} },
                   { 2, GenRules{} },
                   { 3, GenRules{} },
                   { 40, GenRules{} },
                   { 41, GenRules{} },
                   { 91, GenRules{} },
                   { 93, GenRules{} },
                   { 123, GenRules{} },
                   { 125, GenRules{} },
                   { 44, GenRules{ {"44", "1", "B", "Q" }, { 0, 1006, 0, 1009 } } },
                   { 43, GenRules{} },
                   { 45, GenRules{} },
                   { 42, GenRules{} },
                   { 47, GenRules{} },
                   { 61, GenRules{} },
                   { 60, GenRules{} },
                   { 7, GenRules{} },
                   { 5, GenRules{} },
                   { 4, GenRules{} },
                   { 6, GenRules{} },
                   { 62, GenRules{} },
                   { 59, GenRules{} },
                   { 8, GenRules{} },
                   { 33, GenRules{} },
                   { 9, GenRules{} },
                   { 20, GenRules{} },
                   { 21, GenRules{} },
                   { 10, GenRules{} },
                   { 11, GenRules{} },
                   { 12, GenRules{} },
                   { 13, GenRules{} },
                   { 14, GenRules{} },
                   { 15, GenRules{} },
                   { 16, GenRules{} },
                   { 17, GenRules{} },
                   { 18, GenRules{} },
                   { 19, GenRules{} },
                   { 22, GenRules{} },
                   }},
    { GenState::B, {
                   { 1, GenRules{} },
                   { 2, GenRules{} },
                   { 3, GenRules{} },
                   { 40, GenRules{} },
                   { 41, GenRules{} },
                   { 91, GenRules{ {"91", "2", "93", "C" }, { 0, 2, 0, 0 } } },
                   { 93, GenRules{} },
                   { 123, GenRules{} },
                   { 125, GenRules{} },
                   { 44, GenRules{} },
                   { 43, GenRules{} },
                   { 45, GenRules{} },
                   { 42, GenRules{} },
                   { 47, GenRules{} },
                   { 61, GenRules{ {"61", "S", "Z" }, { 1007, 0, 61 } } },
                   { 60, GenRules{} },
                   { 7, GenRules{} },
                   { 5, GenRules{} },
                   { 4, GenRules{} },
                   { 6, GenRules{} },
                   { 62, GenRules{} },
                   { 59, GenRules{} },
                   { 8, GenRules{} },
                   { 33, GenRules{} },
                   { 9, GenRules{} },
                   { 20, GenRules{} },
                   { 21, GenRules{} },
                   { 10, GenRules{} },
                   { 11, GenRules{} },
                   { 12, GenRules{} },
                   { 13, GenRules{} },
                   { 14, GenRules{} },
                   { 15, GenRules{} },
                   { 16, GenRules{} },
                   { 17, GenRules{} },
                   { 18, GenRules{} },
                   { 19, GenRules{} },
                   { 22, GenRules{} },
                   }},
    { GenState::C, {
                   { 1, GenRules{} },
                   { 2, GenRules{} },
                   { 3, GenRules{} },
                   { 40, GenRules{} },
                   { 41, GenRules{} },
                   { 91, GenRules{} },
                   { 93, GenRules{} },
                   { 123, GenRules{} },
                   { 125, GenRules{} },
                   { 44, GenRules{} },
                   { 43, GenRules{} },
                   { 45, GenRules{} },
                   { 42, GenRules{} },
                   { 47, GenRules{} },
                   { 61, GenRules{ { "61", "123", "S", "D", "125" }, { 0, 0, 0, 0, 1008 } } },
                   { 60, GenRules{} },
                   { 7, GenRules{} },
                   { 5, GenRules{} },
                   { 4, GenRules{} },
                   { 6, GenRules{} },
                   { 62, GenRules{} },
                   { 59, GenRules{} },
                   { 8, GenRules{} },
                   { 33, GenRules{} },
                   { 9, GenRules{} },
                   { 20, GenRules{} },
                   { 21, GenRules{} },
                   { 10, GenRules{} },
                   { 11, GenRules{} },
                   { 12, GenRules{} },
                   { 13, GenRules{} },
                   { 14, GenRules{} },
                   { 15, GenRules{} },
                   { 16, GenRules{} },
                   { 17, GenRules{} },
                   { 18, GenRules{} },
                   { 19, GenRules{} },
                   { 22, GenRules{} },
                   }},
    { GenState::D, {
                   { 1, GenRules{} },
                   { 2, GenRules{} },
                   { 3, GenRules{} },
                   { 40, GenRules{} },
                   { 41, GenRules{} },
                   { 91, GenRules{} },
                   { 93, GenRules{} },
                   { 123, GenRules{} },
                   { 125, GenRules{} },
                   { 44, GenRules{ { "44", "S", "D" }, { 0, 0, 0 } } },
                   { 43, GenRules{} },
                   { 45, GenRules{} },
                   { 42, GenRules{} },
                   { 47, GenRules{} },
                   { 61, GenRules{} },
                   { 60, GenRules{} },
                   { 7, GenRules{} },
                   { 5, GenRules{} },
                   { 4, GenRules{} },
                   { 6, GenRules{} },
                   { 62, GenRules{} },
                   { 59, GenRules{} },
                   { 8, GenRules{} },
                   { 33, GenRules{} },
                   { 9, GenRules{} },
                   { 20, GenRules{} },
                   { 21, GenRules{} },
                   { 10, GenRules{} },
                   { 11, GenRules{} },
                   { 12, GenRules{} },
                   { 13, GenRules{} },
                   { 14, GenRules{} },
                   { 15, GenRules{} },
                   { 16, GenRules{} },
                   { 17, GenRules{} },
                   { 18, GenRules{} },
                   { 19, GenRules{} },
                   { 22, GenRules{} },
                   }},
    { GenState::S, {
                   { 1, GenRules{ {"1", "H", "V", "U" }, { 1, 0, 0, 0 } } },
                   { 2, GenRules{ {"2", "V", "U" }, { 2, 0, 0 } } },
                   { 3, GenRules{ {"3", "V", "U" }, { 3, 0, 0 } } },
                   { 40, GenRules{ {"40", "S", "41", "V", "U" }, { 0, 0, 0, 0, 0 } } },
                   { 45, GenRules{ {"45", "G", "V", "U" }, { 0, 0, 1100, 0 } } },
                   { 15, GenRules{ {"15", "40", "S", "41", "V", "U" }, { 0, 0, 0, 1103, 0, 0 } } },
                   { 16, GenRules{ {"16", "40", "S", "41", "V", "U" }, { 0, 0, 0, 1104, 0, 0 } } },
                   { 17, GenRules{ {"17", "40", "S", "41", "V", "U" }, { 0, 0, 0, 1105, 0, 0 } } },
                   { 18, GenRules{ {"18", "40", "S", "41", "V", "U" }, { 0, 0, 0, 1106, 0, 0 } } },
                   { 19, GenRules{ {"19", "40", "S", "41", "V", "U" }, { 0, 0, 0, 1107, 0, 0 } } },
                   }},
    { GenState::U, {
                   { 1, GenRules{} },
                   { 2, GenRules{} },
                   { 3, GenRules{} },
                   { 40, GenRules{} },
                   { 41, GenRules{} },
                   { 91, GenRules{} },
                   { 93, GenRules{} },
                   { 123, GenRules{} },
                   { 125, GenRules{} },
                   { 44, GenRules{} },
                   { 43, GenRules{ {"43", "T", "U" }, { 0, 0, 43 } } },
                   { 45, GenRules{ {"45", "T", "U" }, { 0, 0, 45 } } },
                   { 42, GenRules{} },
                   { 47, GenRules{} },
                   { 61, GenRules{} },
                   { 60, GenRules{} },
                   { 7, GenRules{} },
                   { 5, GenRules{} },
                   { 4, GenRules{} },
                   { 6, GenRules{} },
                   { 62, GenRules{} },
                   { 59, GenRules{} },
                   { 8, GenRules{} },
                   { 33, GenRules{} },
                   { 9, GenRules{} },
                   { 20, GenRules{} },
                   { 21, GenRules{} },
                   { 10, GenRules{} },
                   { 11, GenRules{} },
                   { 12, GenRules{} },
                   { 13, GenRules{} },
                   { 14, GenRules{} },
                   { 15, GenRules{} },
                   { 16, GenRules{} },
                   { 17, GenRules{} },
                   { 18, GenRules{} },
                   { 19, GenRules{} },
                   { 22, GenRules{} },
                   }},
    { GenState::T, {
                   { 1, GenRules{ {"1", "H", "V" }, { 1, 0, 0 } } },
                   { 2, GenRules{ {"2", "V" }, { 2, 0 } } },
                   { 3, GenRules{ {"3", "V" }, { 3, 0 } } },
                   { 40, GenRules{ {"40", "S", "41", "V" }, { 0, 0, 0, 0 } } },
                   { 45, GenRules{ {"45", "G", "V"}, { 0, 0, 1100 } } },
                   { 15, GenRules{ {"15", "40", "S", "41", "V" }, { 0, 0, 0, 1103, 0 } } },
                   { 16, GenRules{ {"16", "40", "S", "41", "V" }, { 0, 0, 0, 1104, 0 } } },
                   { 17, GenRules{ {"17", "40", "S", "41", "V" }, { 0, 0, 0, 1105, 0 } } },
                   { 18, GenRules{ {"18", "40", "S", "41", "V" }, { 0, 0, 0, 1106, 0 } } },
                   { 19, GenRules{ {"19", "40", "S", "41", "V" }, { 0, 0, 0, 1107, 0 } } },
                   }},
    { GenState::V, {
                   { 1, GenRules{} },
                   { 2, GenRules{} },
                   { 3, GenRules{} },
                   { 40, GenRules{} },
                   { 41, GenRules{} },
                   { 91, GenRules{} },
                   { 93, GenRules{} },
                   { 123, GenRules{} },
                   { 125, GenRules{} },
                   { 44, GenRules{} },
                   { 43, GenRules{} },
                   { 45, GenRules{} },
                   { 42, GenRules{ {"42", "F", "V" }, { 0, 0, 42 } } },
                   { 47, GenRules{ {"47", "F", "V" }, { 0, 0, 47 } } },
                   { 61, GenRules{} },
                   { 60, GenRules{} },
                   { 7, GenRules{} },
                   { 5, GenRules{} },
                   { 4, GenRules{} },
                   { 6, GenRules{} },
                   { 62, GenRules{} },
                   { 59, GenRules{} },
                   { 8, GenRules{} },
                   { 33, GenRules{} },
                   { 9, GenRules{} },
                   { 20, GenRules{} },
                   { 21, GenRules{} },
                   { 10, GenRules{} },
                   { 11, GenRules{} },
                   { 12, GenRules{} },
                   { 13, GenRules{} },
                   { 14, GenRules{} },
                   { 15, GenRules{} },
                   { 16, GenRules{} },
                   { 17, GenRules{} },
                   { 18, GenRules{} },
                   { 19, GenRules{} },
                   { 22, GenRules{} },
                   }},
    { GenState::F, {
                   { 1, GenRules{ {"1", "H" }, { 1, 0 } } },
                   { 2, GenRules{ {"2" }, { 2 } } },
                   { 3, GenRules{ {"3" }, { 3 } } },
                   { 40, GenRules{ {"40", "S", "41" }, { 0, 0, 0 } } },
                   { 45, GenRules{ {"45", "G", "Z"}, { 0, 0, 1100 } } },
                   { 15, GenRules{ {"15", "40", "S", "41" }, { 0, 0, 0, 1103 } } },
                   { 16, GenRules{ {"16", "40", "S", "41" }, { 0, 0, 0, 1104 } } },
                   { 17, GenRules{ {"17", "40", "S", "41" }, { 0, 0, 0, 1105 } } },
                   { 18, GenRules{ {"18", "40", "S", "41" }, { 0, 0, 0, 1106 } } },
                   { 19, GenRules{ {"19", "40", "S", "41" }, { 0, 0, 0, 1107 } } },
                   }},
    { GenState::G, {
                   { 1, GenRules{ {"1", "H" }, { 1, 0 } } },
                   { 2, GenRules{ {"2" }, { 2 } } },
                   { 3, GenRules{ {"3" }, { 3 } } },
                   { 40, GenRules{ {"40", "S", "41" }, { 0, 0, 0 } } },
                   { 15, GenRules{ {"15", "40", "S", "41" }, { 0, 0, 0, 1103 } } },
                   { 16, GenRules{ {"16", "40", "S", "41" }, { 0, 0, 0, 1104 } } },
                   { 17, GenRules{ {"17", "40", "S", "41" }, { 0, 0, 0, 1105 } } },
                   { 18, GenRules{ {"18", "40", "S", "41" }, { 0, 0, 0, 1106 } } },
                   { 19, GenRules{ {"19", "40", "S", "41" }, { 0, 0, 0, 1107 } } },
                   }},
    { GenState::H, {
                   { 1, GenRules{} },
                   { 2, GenRules{} },
                   { 3, GenRules{} },
                   { 40, GenRules{} },
                   { 41, GenRules{} },
                   { 91, GenRules{ {"91", "S", "93" }, { 0, 0, 1108 } } },
                   { 93, GenRules{} },
                   { 123, GenRules{} },
                   { 125, GenRules{} },
                   { 44, GenRules{} },
                   { 43, GenRules{} },
                   { 45, GenRules{} },
                   { 42, GenRules{} },
                   { 47, GenRules{} },
                   { 61, GenRules{} },
                   { 60, GenRules{} },
                   { 7, GenRules{} },
                   { 5, GenRules{} },
                   { 4, GenRules{} },
                   { 6, GenRules{} },
                   { 62, GenRules{} },
                   { 59, GenRules{} },
                   { 8, GenRules{} },
                   { 33, GenRules{} },
                   { 9, GenRules{} },
                   { 20, GenRules{} },
                   { 21, GenRules{} },
                   { 10, GenRules{} },
                   { 11, GenRules{} },
                   { 12, GenRules{} },
                   { 13, GenRules{} },
                   { 14, GenRules{} },
                   { 15, GenRules{} },
                   { 16, GenRules{} },
                   { 17, GenRules{} },
                   { 18, GenRules{} },
                   { 19, GenRules{} },
                   { 22, GenRules{} },
                   }},
    { GenState::L, {
                   { 1, GenRules{ {"1", "H", "V", "U", "O", "X", "W" }, { 1, 0, 0, 0, 0, 0, 0 } } },
                   { 2, GenRules{ {"2", "V", "U", "O", "X", "W" }, { 2, 0, 0, 0, 0, 0 } } },
                   { 3, GenRules{ {"3", "V", "U", "O", "X", "W" }, { 3, 0, 0, 0, 0, 0 } } },
                   { 40, GenRules{ {"40", "L", "41", "X", "W" }, { 0, 0, 0, 0, 0 } } },
                   { 45, GenRules{ {"45", "G", "Z", "V", "U", "O", "X", "W" }, { 0, 0, 1100, 0, 0, 0, 0, 0 } } },
                   { 33, GenRules{ {"33", "40", "L", "41", "X", "W" }, { 0, 0, 0, 0, 33, 0 } } },
                   { 15, GenRules{ {"15", "40", "S", "41", "V", "U", "O", "X", "W" }, { 0, 0, 0, 1103, 0, 0, 0, 0, 0 } } },
                   { 16, GenRules{ {"16", "40", "S", "41", "V", "U", "O", "X", "W" }, { 0, 0, 0, 1104, 0, 0, 0, 0, 0  } } },
                   { 17, GenRules{ {"17", "40", "S", "41", "V", "U", "O", "X", "W" }, { 0, 0, 0, 1105, 0, 0, 0, 0, 0  } } },
                   { 18, GenRules{ {"18", "40", "S", "41", "V", "U", "O", "X", "W" }, { 0, 0, 0, 1106, 0, 0, 0, 0, 0  } } },
                   { 19, GenRules{ {"19", "40", "S", "41", "V", "U", "O", "X", "W" }, { 0, 0, 0, 1107, 0, 0, 0, 0, 0  } } },
                   }},
    { GenState::W, {
                   { 1, GenRules{} },
                   { 2, GenRules{} },
                   { 3, GenRules{} },
                   { 40, GenRules{} },
                   { 41, GenRules{} },
                   { 91, GenRules{} },
                   { 93, GenRules{} },
                   { 123, GenRules{} },
                   { 125, GenRules{} },
                   { 44, GenRules{} },
                   { 43, GenRules{} },
                   { 45, GenRules{} },
                   { 42, GenRules{} },
                   { 47, GenRules{} },
                   { 61, GenRules{} },
                   { 60, GenRules{} },
                   { 7, GenRules{} },
                   { 5, GenRules{} },
                   { 4, GenRules{} },
                   { 6, GenRules{} },
                   { 62, GenRules{} },
                   { 59, GenRules{} },
                   { 8, GenRules{ {"8", "M", "W" }, { 0, 0, 8 } } },
                   { 33, GenRules{} },
                   { 9, GenRules{} },
                   { 20, GenRules{} },
                   { 21, GenRules{} },
                   { 10, GenRules{} },
                   { 11, GenRules{} },
                   { 12, GenRules{} },
                   { 13, GenRules{} },
                   { 14, GenRules{} },
                   { 15, GenRules{} },
                   { 16, GenRules{} },
                   { 17, GenRules{} },
                   { 18, GenRules{} },
                   { 19, GenRules{} },
                   { 22, GenRules{} },
                   }},
    { GenState::M, {
                   { 1, GenRules{ {"1", "H", "V", "U", "O", "X" }, { 1, 0, 0, 0, 0, 0  } } },
                   { 2, GenRules{ {"2", "V", "U", "O", "X" }, { 2, 0, 0, 0, 0  } } },
                   { 3, GenRules{ {"3", "V", "U", "O", "X" }, { 3, 0, 0, 0, 0  } } },
                   { 40, GenRules{ {"40", "L", "41", "X" }, { 0, 0, 0, 0  } } },
                   { 45, GenRules{ {"45", "G", "Z", "V", "U", "O", "X" }, { 0, 0, 1100, 0, 0, 0, 0  } } },
                   { 33, GenRules{ {"33", "40", "L", "41", "X" }, { 0, 0, 0, 0, 33 } } },
                   { 15, GenRules{ {"15", "40", "S", "41", "V", "U", "O", "X" }, { 0, 0, 0, 1103, 0, 0, 0, 0  } } },
                   { 16, GenRules{ {"16", "40", "S", "41", "V", "U", "O", "X" }, { 0, 0, 0, 1104, 0, 0, 0, 0  } } },
                   { 17, GenRules{ {"17", "40", "S", "41", "V", "U", "O", "X" }, { 0, 0, 0, 1105, 0, 0, 0, 0  } } },
                   { 18, GenRules{ {"18", "40", "S", "41", "V", "U", "O", "X" }, { 0, 0, 0, 1106, 0, 0, 0, 0  } } },
                   { 19, GenRules{ {"19", "40", "S", "41", "V", "U", "O", "X" }, { 0, 0, 0, 1107, 0, 0, 0, 0  } } },
                   }},
    { GenState::X, {
                   { 1, GenRules{} },
                   { 2, GenRules{} },
                   { 3, GenRules{} },
                   { 40, GenRules{} },
                   { 41, GenRules{} },
                   { 91, GenRules{} },
                   { 93, GenRules{} },
                   { 123, GenRules{} },
                   { 125, GenRules{} },
                   { 44, GenRules{} },
                   { 43, GenRules{} },
                   { 45, GenRules{} },
                   { 42, GenRules{} },
                   { 47, GenRules{} },
                   { 61, GenRules{} },
                   { 60, GenRules{} },
                   { 7, GenRules{} },
                   { 5, GenRules{} },
                   { 4, GenRules{} },
                   { 6, GenRules{} },
                   { 62, GenRules{} },
                   { 59, GenRules{} },
                   { 8, GenRules{} },
                   { 33, GenRules{} },
                   { 9, GenRules{ {"9", "N", "X" }, { 0, 0, 9 } } },
                   { 20, GenRules{} },
                   { 21, GenRules{} },
                   { 10, GenRules{} },
                   { 11, GenRules{} },
                   { 12, GenRules{} },
                   { 13, GenRules{} },
                   { 14, GenRules{} },
                   { 15, GenRules{} },
                   { 16, GenRules{} },
                   { 17, GenRules{} },
                   { 18, GenRules{} },
                   { 19, GenRules{} },
                   { 22, GenRules{} },
                   }},
    { GenState::N, {
                   { 1, GenRules{ {"1", "H", "V", "U", "O" }, { 1, 0, 0, 0, 0  } } },
                   { 2, GenRules{ {"2", "V", "U", "O" }, { 2, 0, 0, 0  } } },
                   { 3, GenRules{ {"3", "V", "U", "O" }, { 3, 0, 0, 0  } } },
                   { 40, GenRules{ {"40", "L", "41" }, { 0, 0, 0  } } },
                   { 45, GenRules{ {"45", "G", "Z", "V", "U", "O" }, { 0, 0, 1100, 0, 0, 0  } } },
                   { 33, GenRules{ {"33", "40", "L", "41", "Z" }, { 0, 0, 0, 0, 33 } } },
                   { 15, GenRules{ {"15", "40", "S", "41", "V", "U", "O" }, { 0, 0, 0, 1103, 0, 0, 0  } } },
                   { 16, GenRules{ {"16", "40", "S", "41", "V", "U", "O" }, { 0, 0, 0, 1104, 0, 0, 0  } } },
                   { 17, GenRules{ {"17", "40", "S", "41", "V", "U", "O" }, { 0, 0, 0, 1105, 0, 0, 0  } } },
                   { 18, GenRules{ {"18", "40", "S", "41", "V", "U", "O" }, { 0, 0, 0, 1106, 0, 0, 0  } } },
                   { 19, GenRules{ {"19", "40", "S", "41", "V", "U", "O" }, { 0, 0, 0, 1107, 0, 0, 0  } } },
                   }},
    { GenState::O, {
                   { 60, GenRules{ {"60", "S", "Z" }, { 0, 0, 60 } } },
                   { 7, GenRules{ {"7", "S", "Z" }, { 0, 0, 7 } } },
                   { 5, GenRules{ {"5", "S", "Z" }, { 0, 0, 5 } } },
                   { 4, GenRules{ {"4", "S", "Z" }, { 0, 0, 4 } } },
                   { 6, GenRules{ {"6", "S", "Z" }, { 0, 0, 6 } } },
                   { 62, GenRules{ {"62", "S", "Z" }, { 0, 0, 62 } } },
                   }},
    { GenState::E, {
                   { 1, GenRules{} },
                   { 2, GenRules{} },
                   { 3, GenRules{} },
                   { 40, GenRules{} },
                   { 41, GenRules{} },
                   { 91, GenRules{} },
                   { 93, GenRules{} },
                   { 123, GenRules{} },
                   { 125, GenRules{} },
                   { 44, GenRules{} },
                   { 43, GenRules{} },
                   { 45, GenRules{} },
                   { 42, GenRules{} },
                   { 47, GenRules{} },
                   { 61, GenRules{} },
                   { 60, GenRules{} },
                   { 7, GenRules{} },
                   { 5, GenRules{} },
                   { 4, GenRules{} },
                   { 6, GenRules{} },
                   { 62, GenRules{} },
                   { 59, GenRules{} },
                   { 8, GenRules{} },
                   { 33, GenRules{} },
                   { 9, GenRules{} },
                   { 20, GenRules{} },
                   { 21, GenRules{} },
                   { 10, GenRules{} },
                   { 11, GenRules{ {"11", "123", "A", "125" }, { 1002, 0, 0, 0 } } },
                   { 12, GenRules{} },
                   { 13, GenRules{} },
                   { 14, GenRules{} },
                   { 15, GenRules{} },
                   { 16, GenRules{} },
                   { 17, GenRules{} },
                   { 18, GenRules{} },
                   { 19, GenRules{} },
                   { 22, GenRules{} },
                   }},
    { GenState::Z, {
                   { 1, GenRules{} },
                   { 2, GenRules{} },
                   { 3, GenRules{} },
                   { 40, GenRules{} },
                   { 41, GenRules{} },
                   { 91, GenRules{} },
                   { 93, GenRules{} },
                   { 123, GenRules{} },
                   { 125, GenRules{} },
                   { 44, GenRules{} },
                   { 43, GenRules{} },
                   { 45, GenRules{} },
                   { 42, GenRules{} },
                   { 47, GenRules{} },
                   { 61, GenRules{} },
                   { 60, GenRules{} },
                   { 7, GenRules{} },
                   { 5, GenRules{} },
                   { 4, GenRules{} },
                   { 6, GenRules{} },
                   { 62, GenRules{} },
                   { 59, GenRules{} },
                   { 8, GenRules{} },
                   { 33, GenRules{} },
                   { 9, GenRules{} },
                   { 20, GenRules{} },
                   { 21, GenRules{} },
                   { 10, GenRules{} },
                   { 11, GenRules{} },
                   { 12, GenRules{} },
                   { 13, GenRules{} },
                   { 14, GenRules{} },
                   { 15, GenRules{} },
                   { 16, GenRules{} },
                   { 17, GenRules{} },
                   { 18, GenRules{} },
                   { 19, GenRules{} },
                   { 22, GenRules{} },
                   }}
};

#endif // GENOPS_H